// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SomeTaco.Database;

#nullable disable

namespace EfCorePaging.Server.Migrations
{
    [DbContext(typeof(SomeTacoContext))]
    partial class SomeTacoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SomeTaco.Models.Taco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Tacos");
                });

            modelBuilder.Entity("SomeTaco.Models.Topping", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Toppings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "None"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Spinach"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cucumber"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Spoon"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hair"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mouse"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Coffee"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Microphone"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Bacon"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Egg"
                        },
                        new
                        {
                            Id = 12,
                            Name = "England"
                        },
                        new
                        {
                            Id = 13,
                            Name = "CabbageSlaw"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Pineapple"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Salsa"
                        },
                        new
                        {
                            Id = 17,
                            Name = "SourCream"
                        },
                        new
                        {
                            Id = 18,
                            Name = "SourCreme"
                        },
                        new
                        {
                            Id = 19,
                            Name = "CremeDeMinth"
                        },
                        new
                        {
                            Id = 20,
                            Name = "DicedTomatoes"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Lettuce"
                        },
                        new
                        {
                            Id = 22,
                            Name = "GroundBeef"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Chorizo"
                        },
                        new
                        {
                            Id = 25,
                            Name = "PintoBeans"
                        },
                        new
                        {
                            Id = 26,
                            Name = "RefriedBeans"
                        },
                        new
                        {
                            Id = 27,
                            Name = "WhiteBeans"
                        },
                        new
                        {
                            Id = 28,
                            Name = "BlackBeans"
                        },
                        new
                        {
                            Id = 29,
                            Name = "RedKidneyBeans"
                        },
                        new
                        {
                            Id = 30,
                            Name = "EvenMoreBacon"
                        },
                        new
                        {
                            Id = 31,
                            Name = "BeefSteak"
                        },
                        new
                        {
                            Id = 32,
                            Name = "PulledPork"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Stake"
                        },
                        new
                        {
                            Id = 34,
                            Name = "BbqPork"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 36,
                            Name = "BatteredFish"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Barnacles"
                        });
                });

            modelBuilder.Entity("TacoTopping", b =>
                {
                    b.Property<int>("TacosId")
                        .HasColumnType("int");

                    b.Property<int>("ToppingsId")
                        .HasColumnType("int");

                    b.HasKey("TacosId", "ToppingsId");

                    b.HasIndex("ToppingsId");

                    b.ToTable("TacoTopping");
                });

            modelBuilder.Entity("TacoTopping", b =>
                {
                    b.HasOne("SomeTaco.Models.Taco", null)
                        .WithMany()
                        .HasForeignKey("TacosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SomeTaco.Models.Topping", null)
                        .WithMany()
                        .HasForeignKey("ToppingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
